import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";
import Navbar from "../components/navbar";

const inter = Poppins({ weight: "400", subsets: ['devanagari'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
          {children}

      
      </body>
    </html>
  );
}
